### ISSUE TITLE
Make mmap capability per-thread

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribsd#229]
@davidchisnall suggests that the mmap capability should be per-thread "so you could have a privileged thread that can allocate memory but not permit others to create or modify mappings."

**Comment by davidchisnall** [comment]
This would be potentially interesting for GC, because (with some refinements to signal handling semantics) the GC thread could then be split off from the main thread prior to main and the main thread be prevented from issuing the mmap system call directly.  The mmap interposition wrapper would request that the GC thread perform mmap on its behalf, and all of the collector state could live in a region outside of the main program's DDC.
